# Generated by Django 5.2.3 on 2025-06-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20)),
                ('nombreconfig', models.CharField(max_length=100)),
                ('telefonoconfig', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('razonsocial', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
