# Generated by Django 5.2.3 on 2025-06-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreuser', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('correouser', models.EmailField(blank=True, max_length=100, null=True)),
                ('clave', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('admin', 'Admin'), ('vendedor', 'Vendedor')], default='vendedor', max_length=10)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
