# Generated by Django 5.2.3 on 2025-06-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cicli', models.CharField(max_length=20)),
                ('nombrecli', models.CharField(max_length=100)),
                ('direccioncli', models.CharField(blank=True, max_length=150, null=True)),
                ('telefonocli', models.CharField(blank=True, max_length=20, null=True)),
                ('estadocli', models.BooleanField(default=True)),
            ],
        ),
    ]
